// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVKG5zpYhMdMn-vJa42nTyri-XlUp_kw',
    appId: '1:71215710461:web:eb753edbc44539e374fe94',
    messagingSenderId: '71215710461',
    projectId: 'linkhub-pakuan',
    authDomain: 'linkhub-pakuan.firebaseapp.com',
    storageBucket: 'linkhub-pakuan.firebasestorage.app',
    measurementId: 'G-2VXZ1HKHD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr78_CyFyccVWFzXb5e8XkF3b491Ef0To',
    appId: '1:71215710461:android:b193e5e899862dbd74fe94',
    messagingSenderId: '71215710461',
    projectId: 'linkhub-pakuan',
    storageBucket: 'linkhub-pakuan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMaJqj3Srehtha0J0nwZg4PTcuiKOEbU',
    appId: '1:71215710461:ios:14ab3741a5d2315174fe94',
    messagingSenderId: '71215710461',
    projectId: 'linkhub-pakuan',
    storageBucket: 'linkhub-pakuan.firebasestorage.app',
    iosBundleId: 'com.example.linkhubpakuan',
  );
}
